# Generated by Django 3.0.2 on 2020-01-17 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%Y/%m/%d/orig')),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('studyDate', models.DateField(default=datetime.date.today)),
                ('author', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
