# Generated by Django 3.0.1 on 2020-01-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%Y/%m/%d/orig')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
