# Generated by Django 3.0.2 on 2020-02-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_data_when_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
