# Generated by Django 3.0.1 on 2020-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_data_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupNo', models.IntegerField()),
                ('stuID', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('phoneNo', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
            ],
        ),
    ]
