# Generated by Django 3.0.2 on 2020-02-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
