# Generated by Django 2.2.9 on 2020-02-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200202_1258'),
        ('photos', '0005_verification'),
    ]

    operations = [
    ]
