# Generated by Django 3.0.1 on 2020-02-26 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_delete_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
