# Generated by Django 3.0.1 on 2020-02-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_merge_20200203_0558'),
        ('photos', '0003_alarm'),
    ]

    operations = [
    ]
