# Generated by Django 2.1 on 2020-02-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
