# Generated by Django 3.0.2 on 2020-02-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_merge_20200203_0716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
