# Generated by Django 3.0.1 on 2020-02-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
