# Generated by Django 2.1 on 2020-03-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_member_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
