# Generated by Django 3.0.1 on 2020-02-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_userinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
