# Generated by Django 3.0.1 on 2020-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='participator',
            field=models.ManyToManyField(to='photos.Member'),
        ),
    ]
