# Generated by Django 3.0.1 on 2020-03-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_data_study_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='idgroup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
