# Generated by Django 3.0.1 on 2020-03-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_data_idgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
