# Generated by Django 2.1 on 2020-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20200322_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='when_saved',
            new_name='code_when_saved',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='study_time',
            new_name='study_start_time',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='when_saved',
            new_name='code_when_saved',
        ),
        migrations.AddField(
            model_name='data',
            name='study_total_duration',
            field=models.IntegerField(default=0),
        ),
    ]
