# Generated by Django 2.1 on 2020-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20200327_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='study_start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
